
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package be.ac.ulg.vsop.parser;

/** CUP generated class containing symbol constants. */
public class SymbolValue {
  /* terminals */
  public static final int LBRK = 50;
  public static final int TYPE_IDENTIFIER = 39;
  public static final int POW = 31;
  public static final int STRING_LITERAL = 40;
  public static final int INT32 = 11;
  public static final int UNIT = 42;
  public static final int LOWER = 33;
  public static final int GREATER = 44;
  public static final int MINUS = 28;
  public static final int NOT = 15;
  public static final int SEMICOLON = 25;
  public static final int AND = 2;
  public static final int RPAR = 23;
  public static final int OR = 46;
  public static final int IN = 10;
  public static final int BOOL = 3;
  public static final int COMMA = 26;
  public static final int CLASS = 4;
  public static final int DIV = 30;
  public static final int PLUS = 27;
  public static final int ASSIGN = 35;
  public static final int IF = 9;
  public static final int DOT = 36;
  public static final int RBRK = 51;
  public static final int EOF = 0;
  public static final int EQUAL = 32;
  public static final int GREATER_EQUAL = 45;
  public static final int TRUE = 18;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int ISNULL = 12;
  public static final int NULL = 41;
  public static final int SWITCH = 49;
  public static final int TIMES = 29;
  public static final int COLON = 24;
  public static final int UNIT_VALUE = 43;
  public static final int LBRACE = 20;
  public static final int ELSE = 6;
  public static final int WHILE = 19;
  public static final int FLOAT = 47;
  public static final int LET = 13;
  public static final int THEN = 17;
  public static final int RBRACE = 21;
  public static final int LOWER_EQUAL = 34;
  public static final int EXTENDS = 7;
  public static final int LPAR = 22;
  public static final int STRING = 16;
  public static final int FLOAT_LITERAL = 48;
  public static final int FALSE = 8;
  public static final int DO = 5;
  public static final int OBJECT_IDENTIFIER = 38;
  public static final int INTEGER_LITERAL = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "BOOL",
  "CLASS",
  "DO",
  "ELSE",
  "EXTENDS",
  "FALSE",
  "IF",
  "IN",
  "INT32",
  "ISNULL",
  "LET",
  "NEW",
  "NOT",
  "STRING",
  "THEN",
  "TRUE",
  "WHILE",
  "LBRACE",
  "RBRACE",
  "LPAR",
  "RPAR",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "EQUAL",
  "LOWER",
  "LOWER_EQUAL",
  "ASSIGN",
  "DOT",
  "INTEGER_LITERAL",
  "OBJECT_IDENTIFIER",
  "TYPE_IDENTIFIER",
  "STRING_LITERAL",
  "NULL",
  "UNIT",
  "UNIT_VALUE",
  "GREATER",
  "GREATER_EQUAL",
  "OR",
  "FLOAT",
  "FLOAT_LITERAL",
  "SWITCH",
  "LBRK",
  "RBRK"
  };
}

