/* The following code was generated by JFlex 1.6.1 */

/*VSOP Parser*/
package be.ac.ulg.vsop.lexer;
import be.ac.ulg.vsop.parser.SymbolValue;
import java.util.Stack;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>E:/m1prg/Compiler/Parsers/VSOPParser.flex</tt>
 */
class VSOPParser {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;
  public static final int ERROR = 6;
  public static final int HEX = 8;
  public static final int BIN = 10;
  public static final int BYTESTRING = 12;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6, 6
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\1\57\10\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\0"+
    "\1\36\5\0\1\41\1\42\1\50\1\46\1\45\1\47\1\5\1\4"+
    "\1\35\1\55\1\27\1\26\6\10\1\43\1\44\1\53\1\52\3\0"+
    "\6\54\24\6\1\0\1\56\1\0\1\51\1\7\1\0\1\11\1\14"+
    "\1\17\1\13\1\21\1\24\1\33\1\34\1\25\2\7\1\16\1\7"+
    "\1\12\1\15\2\7\1\32\1\20\1\23\1\30\1\7\1\31\1\22"+
    "\2\7\1\37\1\0\1\40\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\7\0\1\1\2\2\1\3\1\4\21\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\0\1\24\2\23"+
    "\1\25\2\2\1\26\1\27\1\0\1\30\2\0\2\31"+
    "\1\32\2\33\1\0\2\34\1\0\2\35\24\0\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\2\0\1\43\2\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\26\2\60\2\61\1\62\1\32"+
    "\1\63\1\64\1\65\4\0\2\66\11\0\2\67\2\0"+
    "\2\70\3\0\1\71\1\72\2\73\2\74\2\75\2\0"+
    "\2\76\13\0\2\77\2\100\2\0\2\101\1\0\2\102"+
    "\2\103\3\0\2\104\1\0\2\105\2\0\2\106\2\107"+
    "\1\0\2\110\2\111\1\0\2\112\2\113";

  private static int [] zzUnpackAction() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\360\0\u0120\0\u0150"+
    "\0\u0180\0\u0150\0\u01b0\0\u0150\0\u01e0\0\u0210\0\u0240\0\u0270"+
    "\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0"+
    "\0\u0420\0\u0450\0\u0480\0\u04b0\0\u04e0\0\u0150\0\u0150\0\u0150"+
    "\0\u0510\0\u0150\0\u0150\0\u0150\0\u0150\0\u0150\0\u0150\0\u0150"+
    "\0\u0150\0\u0150\0\u0540\0\u0570\0\u0570\0\u0150\0\u05a0\0\u05d0"+
    "\0\u0570\0\u0600\0\u0630\0\u0660\0\u0150\0\u0690\0\u0150\0\u06c0"+
    "\0\u06f0\0\u0150\0\u0720\0\u0750\0\u0780\0\u0150\0\u01e0\0\u07b0"+
    "\0\u0150\0\u0210\0\u07e0\0\u0150\0\u0240\0\u0810\0\u0840\0\u0870"+
    "\0\u08a0\0\u08d0\0\u0900\0\u0930\0\u0960\0\u0990\0\u09c0\0\u09f0"+
    "\0\u0a20\0\u0a50\0\u0a80\0\u0ab0\0\u0ae0\0\u0b10\0\u0b40\0\u0b70"+
    "\0\u0150\0\u0150\0\u0150\0\u0150\0\u0150\0\u0570\0\u05a0\0\u0ba0"+
    "\0\u0150\0\u0150\0\u0bd0\0\u0c00\0\u0150\0\u0150\0\u0150\0\u0150"+
    "\0\u0150\0\u0150\0\u0150\0\u0150\0\u0150\0\u0150\0\u0150\0\u0c30"+
    "\0\u0150\0\u0c60\0\u0150\0\u0150\0\u0150\0\u0150\0\u0150\0\u0150"+
    "\0\u0c90\0\u0cc0\0\u0cf0\0\u0d20\0\u0d50\0\u0150\0\u0d80\0\u0db0"+
    "\0\u0de0\0\u0e10\0\u0e40\0\u0e70\0\u0ea0\0\u0ed0\0\u0f00\0\u0f30"+
    "\0\u0150\0\u0f60\0\u0f90\0\u0fc0\0\u0150\0\u0ff0\0\u1020\0\u0bd0"+
    "\0\u0150\0\u0150\0\u1050\0\u0150\0\u1080\0\u0150\0\u10b0\0\u0150"+
    "\0\u10e0\0\u1110\0\u1140\0\u0150\0\u1170\0\u11a0\0\u11d0\0\u1200"+
    "\0\u1230\0\u1260\0\u1290\0\u12c0\0\u12f0\0\u1320\0\u1350\0\u1380"+
    "\0\u0150\0\u13b0\0\u0150\0\u13e0\0\u1410\0\u1440\0\u0150\0\u1470"+
    "\0\u14a0\0\u0150\0\u14d0\0\u0150\0\u1500\0\u1530\0\u1560\0\u1590"+
    "\0\u0150\0\u15c0\0\u15f0\0\u0150\0\u1620\0\u1650\0\u1680\0\u0150"+
    "\0\u16b0\0\u0150\0\u16e0\0\u1710\0\u0150\0\u1740\0\u0150\0\u1770"+
    "\0\u17a0\0\u0150\0\u17d0\0\u0150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\10\1\11\2\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\16\1\24\1\25\1\26"+
    "\1\27\1\16\1\30\1\31\1\32\2\17\1\33\1\34"+
    "\3\16\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\15\1\17\2\10\2\54\1\55\33\54\1\56\2\54"+
    "\2\57\13\54\1\60\1\61\41\12\1\62\6\12\1\63"+
    "\7\12\2\64\1\0\55\64\10\65\2\66\1\65\2\66"+
    "\2\65\1\66\1\65\1\66\2\65\1\66\1\65\2\66"+
    "\5\65\1\66\16\65\2\66\2\65\10\67\2\70\1\67"+
    "\2\70\2\67\1\70\1\67\1\70\2\67\1\70\1\67"+
    "\2\70\5\67\1\71\16\67\1\70\1\71\2\67\2\72"+
    "\1\0\5\72\2\73\1\72\2\73\2\72\1\73\1\72"+
    "\1\73\2\72\1\73\1\72\2\73\5\72\1\73\16\72"+
    "\2\73\2\72\62\0\1\12\61\0\1\74\54\0\1\75"+
    "\4\76\30\77\1\0\10\76\1\0\4\76\2\77\3\0"+
    "\1\100\4\101\30\102\1\0\10\101\1\0\4\101\2\102"+
    "\3\0\1\103\6\104\1\105\15\104\2\105\5\104\1\105"+
    "\1\0\10\104\1\0\5\104\1\105\3\0\1\100\4\101"+
    "\4\102\1\106\23\102\1\0\10\101\1\0\4\101\2\102"+
    "\3\0\1\100\4\101\7\102\1\107\3\102\1\110\6\102"+
    "\1\111\5\102\1\0\10\101\1\0\4\101\2\102\3\0"+
    "\1\100\4\101\7\102\1\112\20\102\1\0\10\101\1\0"+
    "\4\101\2\102\3\0\1\100\4\101\7\102\1\113\20\102"+
    "\1\0\10\101\1\0\4\101\2\102\3\0\1\100\4\101"+
    "\13\102\1\114\14\102\1\0\10\101\1\0\4\101\2\102"+
    "\3\0\1\100\4\101\10\102\1\115\17\102\1\0\10\101"+
    "\1\0\4\101\2\102\3\0\1\100\4\101\15\102\1\116"+
    "\12\102\1\0\10\101\1\0\4\101\2\102\3\0\1\100"+
    "\4\101\10\102\1\117\3\102\1\120\13\102\1\0\10\101"+
    "\1\0\4\101\2\102\3\0\1\100\4\101\24\102\1\121"+
    "\1\102\1\122\1\102\1\0\10\101\1\0\4\101\2\102"+
    "\3\0\1\100\4\101\3\102\1\123\24\102\1\0\10\101"+
    "\1\0\4\101\2\102\3\0\1\100\4\101\4\102\1\124"+
    "\5\102\1\125\3\102\1\126\11\102\1\0\10\101\1\0"+
    "\4\101\2\102\3\0\1\100\4\101\4\102\1\127\23\102"+
    "\1\0\10\101\1\0\4\101\2\102\3\0\1\100\4\101"+
    "\26\102\1\130\1\102\1\0\10\101\1\0\4\101\2\102"+
    "\3\0\1\103\6\104\1\105\3\104\1\131\5\104\1\132"+
    "\3\104\2\105\5\104\1\105\1\0\10\104\1\0\5\104"+
    "\1\105\52\0\1\133\56\0\1\134\2\0\1\135\5\0"+
    "\2\55\1\136\33\55\1\0\2\55\2\137\13\55\1\0"+
    "\1\55\1\0\1\140\1\141\55\0\1\142\1\143\1\144"+
    "\1\143\6\142\1\145\1\142\1\146\5\142\1\147\1\150"+
    "\1\151\5\142\1\152\3\142\1\153\17\142\1\154\1\142"+
    "\50\0\1\155\51\0\1\156\15\0\2\64\1\157\55\64"+
    "\1\65\1\160\4\161\2\65\2\66\1\65\2\66\2\65"+
    "\1\66\1\65\1\66\2\65\1\66\1\65\2\66\5\65"+
    "\1\66\1\65\10\161\1\65\4\161\2\66\2\65\10\67"+
    "\2\70\1\67\2\70\2\67\1\70\1\67\1\70\2\67"+
    "\1\70\1\67\2\70\5\67\1\70\16\67\2\70\3\67"+
    "\1\162\4\163\2\67\2\70\1\67\2\70\2\67\1\70"+
    "\1\67\1\70\2\67\1\70\1\67\2\70\5\67\1\71"+
    "\1\67\10\163\1\67\4\163\1\70\1\71\2\67\10\0"+
    "\2\164\1\0\2\164\2\0\1\164\1\0\1\164\2\0"+
    "\1\164\1\0\2\164\5\0\1\164\16\0\2\164\2\0"+
    "\2\74\1\165\55\74\2\0\1\166\57\0\1\167\57\0"+
    "\1\170\56\0\1\100\4\101\5\102\1\171\22\102\1\0"+
    "\10\101\1\0\4\101\2\102\3\0\1\100\4\101\15\102"+
    "\1\172\12\102\1\0\10\101\1\0\4\101\2\102\3\0"+
    "\1\100\4\101\23\102\1\173\4\102\1\0\10\101\1\0"+
    "\4\101\2\102\3\0\1\100\4\101\10\102\1\174\17\102"+
    "\1\0\10\101\1\0\4\101\2\102\3\0\1\175\4\176"+
    "\30\102\1\0\10\176\1\0\4\176\2\102\3\0\1\100"+
    "\4\101\7\102\1\177\20\102\1\0\10\101\1\0\4\101"+
    "\2\102\3\0\1\100\4\101\15\102\1\200\12\102\1\0"+
    "\10\101\1\0\4\101\2\102\3\0\1\100\4\101\3\102"+
    "\1\201\24\102\1\0\10\101\1\0\4\101\2\102\3\0"+
    "\1\100\4\101\24\102\1\202\3\102\1\0\10\101\1\0"+
    "\4\101\2\102\3\0\1\100\4\101\12\102\1\203\15\102"+
    "\1\0\10\101\1\0\4\101\2\102\3\0\1\100\4\101"+
    "\15\102\1\204\12\102\1\0\10\101\1\0\4\101\2\102"+
    "\3\0\1\100\4\101\22\102\1\205\5\102\1\0\10\101"+
    "\1\0\4\101\2\102\3\0\1\100\4\101\13\102\1\206"+
    "\14\102\1\0\10\101\1\0\4\101\2\102\3\0\1\100"+
    "\4\101\10\102\1\207\17\102\1\0\10\101\1\0\4\101"+
    "\2\102\3\0\1\210\4\211\15\102\1\212\12\102\1\0"+
    "\10\211\1\0\4\211\2\102\3\0\1\100\4\101\4\102"+
    "\1\213\23\102\1\0\10\101\1\0\4\101\2\102\3\0"+
    "\1\214\4\215\30\102\1\0\10\215\1\0\4\215\2\102"+
    "\3\0\1\100\4\101\17\102\1\216\10\102\1\0\10\101"+
    "\1\0\4\101\2\102\3\0\1\100\4\101\17\102\1\217"+
    "\10\102\1\0\10\101\1\0\4\101\2\102\4\0\1\141"+
    "\56\0\1\220\1\144\1\220\55\0\1\144\1\0\1\144"+
    "\56\0\1\221\57\0\1\222\56\0\1\223\4\224\30\102"+
    "\1\0\10\224\1\0\4\224\2\102\3\0\1\225\4\226"+
    "\30\102\1\0\10\226\1\0\4\226\2\102\3\0\1\227"+
    "\4\230\30\102\1\0\10\230\1\0\4\230\2\102\3\0"+
    "\1\100\4\101\10\102\1\231\17\102\1\0\10\101\1\0"+
    "\4\101\2\102\4\0\1\176\56\0\1\100\4\101\10\102"+
    "\1\232\17\102\1\0\10\101\1\0\4\101\2\102\3\0"+
    "\1\233\4\234\30\102\1\0\10\234\1\0\4\234\2\102"+
    "\3\0\1\100\4\101\12\102\1\235\15\102\1\0\10\101"+
    "\1\0\4\101\2\102\3\0\1\100\4\101\17\102\1\236"+
    "\10\102\1\0\10\101\1\0\4\101\2\102\3\0\1\100"+
    "\4\101\13\102\1\237\14\102\1\0\10\101\1\0\4\101"+
    "\2\102\3\0\1\100\4\101\13\102\1\240\14\102\1\0"+
    "\10\101\1\0\4\101\2\102\3\0\1\100\4\101\13\102"+
    "\1\241\14\102\1\0\10\101\1\0\4\101\2\102\3\0"+
    "\1\100\4\101\4\102\1\242\23\102\1\0\10\101\1\0"+
    "\4\101\2\102\3\0\1\100\4\101\12\102\1\243\15\102"+
    "\1\0\10\101\1\0\4\101\2\102\4\0\1\211\56\0"+
    "\1\100\4\101\20\102\1\244\7\102\1\0\10\101\1\0"+
    "\4\101\2\102\3\0\1\100\4\101\22\102\1\245\5\102"+
    "\1\0\10\101\1\0\4\101\2\102\4\0\1\215\56\0"+
    "\1\100\4\101\15\102\1\246\12\102\1\0\10\101\1\0"+
    "\4\101\2\102\3\0\1\100\4\101\10\102\1\247\17\102"+
    "\1\0\10\101\1\0\4\101\2\102\4\0\1\224\57\0"+
    "\1\226\57\0\1\230\56\0\1\250\4\251\30\102\1\0"+
    "\10\251\1\0\4\251\2\102\3\0\1\252\4\253\30\102"+
    "\1\0\10\253\1\0\4\253\2\102\4\0\1\234\56\0"+
    "\1\100\4\101\12\102\1\254\15\102\1\0\10\101\1\0"+
    "\4\101\2\102\3\0\1\100\4\101\4\102\1\255\23\102"+
    "\1\0\10\101\1\0\4\101\2\102\3\0\1\256\4\257"+
    "\30\102\1\0\10\257\1\0\4\257\2\102\3\0\1\100"+
    "\4\101\4\102\1\260\23\102\1\0\10\101\1\0\4\101"+
    "\2\102\3\0\1\261\4\262\30\102\1\0\10\262\1\0"+
    "\4\262\2\102\3\0\1\263\4\264\30\102\1\0\10\264"+
    "\1\0\4\264\2\102\3\0\1\100\4\101\13\102\1\265"+
    "\14\102\1\0\10\101\1\0\4\101\2\102\3\0\1\100"+
    "\4\101\21\102\1\266\6\102\1\0\10\101\1\0\4\101"+
    "\2\102\3\0\1\100\4\101\10\102\1\267\17\102\1\0"+
    "\10\101\1\0\4\101\2\102\3\0\1\270\4\271\30\102"+
    "\1\0\10\271\1\0\4\271\2\102\3\0\1\100\4\101"+
    "\13\102\1\272\14\102\1\0\10\101\1\0\4\101\2\102"+
    "\4\0\1\251\57\0\1\253\56\0\1\273\4\274\30\102"+
    "\1\0\10\274\1\0\4\274\2\102\3\0\1\100\4\101"+
    "\25\102\1\275\2\102\1\0\10\101\1\0\4\101\2\102"+
    "\4\0\1\257\56\0\1\100\4\101\5\102\1\276\22\102"+
    "\1\0\10\101\1\0\4\101\2\102\4\0\1\262\57\0"+
    "\1\264\56\0\1\277\4\300\30\102\1\0\10\300\1\0"+
    "\4\300\2\102\3\0\1\301\4\302\30\102\1\0\10\302"+
    "\1\0\4\302\2\102\3\0\1\100\4\101\10\102\1\303"+
    "\17\102\1\0\10\101\1\0\4\101\2\102\4\0\1\271"+
    "\56\0\1\304\4\305\30\102\1\0\10\305\1\0\4\305"+
    "\2\102\4\0\1\274\56\0\1\306\4\307\30\102\1\0"+
    "\10\307\1\0\4\307\2\102\3\0\1\100\4\101\12\102"+
    "\1\310\15\102\1\0\10\101\1\0\4\101\2\102\4\0"+
    "\1\300\57\0\1\302\56\0\1\311\4\312\30\102\1\0"+
    "\10\312\1\0\4\312\2\102\4\0\1\305\57\0\1\307"+
    "\56\0\1\313\4\314\30\102\1\0\10\314\1\0\4\314"+
    "\2\102\4\0\1\312\57\0\1\314\55\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6144];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\7\0\1\11\1\1\1\11\1\1\1\11\21\1\3\11"+
    "\1\1\11\11\2\1\1\0\1\11\6\1\1\11\1\0"+
    "\1\11\2\0\1\11\3\1\1\11\1\0\1\1\1\11"+
    "\1\0\1\1\1\11\24\0\5\11\1\1\2\0\2\11"+
    "\2\1\13\11\1\1\1\11\1\1\6\11\4\0\1\1"+
    "\1\11\11\0\1\1\1\11\2\0\1\1\1\11\3\0"+
    "\2\11\1\1\1\11\1\1\1\11\1\1\1\11\2\0"+
    "\1\1\1\11\13\0\1\1\1\11\1\1\1\11\2\0"+
    "\1\1\1\11\1\0\1\1\1\11\1\1\1\11\3\0"+
    "\1\1\1\11\1\0\1\1\1\11\2\0\1\1\1\11"+
    "\1\1\1\11\1\0\1\1\1\11\1\1\1\11\1\0"+
    "\1\1\1\11\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
   StringBuffer string = new StringBuffer();
   int nesting = 0, cbegin = 0, rbegin = 0;
   Stack<Integer> ccomment = new Stack<Integer>(), rcomment = new Stack<Integer>();

   public Symbol symbol(int type) {
      return new Symbol(type, yyline + 1, yycolumn + 1);
   }
   public Symbol symbol(int type, String value) {
      return new Symbol(type, yyline + 1, yycolumn + 1, value);
   }
   public Symbol symbol(int type, String value, int y, int x) {
      return new Symbol(type, y + 1, x + 1, value);
   }
   public Symbol symbol(int type, int value) {
      return new Symbol(type, yyline + 1, yycolumn + 1, value);
   }
   public Symbol symbol(int type, int value, int y, int x) {
      return new Symbol(type, y + 1, x + 1, value);
   }
   public String toPoint(int pt) {
      if(pt < 10)
         return pt + "";
      else if(pt == 10)
         return "a";
      else if(pt == 11)
         return "b";
      else if(pt == 12)
         return "c";
      else if(pt == 13)
         return "d";
      else if(pt == 14)
         return "e";
      else if(pt == 15)
         return "f";
      return "0";
   }
   public String toVSOPString(String text) {
      int point = text.charAt(0);
      if(point > 126 || point < 32) {
         return "\\x" + toPoint(point / 16) + toPoint(point % 16);
      } else
         return text;
   }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  VSOPParser(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 162) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { yybegin(ERROR); yypushback(1);
            }
          case 76: break;
          case 2: 
            { /* ignore */
            }
          case 77: break;
          case 3: 
            { return symbol(SymbolValue.DIV);
            }
          case 78: break;
          case 4: 
            { return symbol(SymbolValue.DOT);
            }
          case 79: break;
          case 5: 
            { cbegin = yycolumn; rbegin = yyline; string.setLength(0); yybegin(STRING); string.append('"');
            }
          case 80: break;
          case 6: 
            { return symbol(SymbolValue.LBRACE);
            }
          case 81: break;
          case 7: 
            { return symbol(SymbolValue.RBRACE);
            }
          case 82: break;
          case 8: 
            { return symbol(SymbolValue.LPAR);
            }
          case 83: break;
          case 9: 
            { return symbol(SymbolValue.RPAR);
            }
          case 84: break;
          case 10: 
            { return symbol(SymbolValue.COLON);
            }
          case 85: break;
          case 11: 
            { return symbol(SymbolValue.SEMICOLON);
            }
          case 86: break;
          case 12: 
            { return symbol(SymbolValue.COMMA);
            }
          case 87: break;
          case 13: 
            { return symbol(SymbolValue.PLUS);
            }
          case 88: break;
          case 14: 
            { return symbol(SymbolValue.MINUS);
            }
          case 89: break;
          case 15: 
            { return symbol(SymbolValue.TIMES);
            }
          case 90: break;
          case 16: 
            { return symbol(SymbolValue.POW);
            }
          case 91: break;
          case 17: 
            { return symbol(SymbolValue.EQUAL);
            }
          case 92: break;
          case 18: 
            { return symbol(SymbolValue.LOWER);
            }
          case 93: break;
          case 19: 
            { string.append(toVSOPString(yytext()));
            }
          case 94: break;
          case 20: 
            { yybegin(YYINITIAL); string.append('"'); return symbol(SymbolValue.STRING_LITERAL, string.toString(), rbegin, cbegin);
            }
          case 95: break;
          case 21: 
            { throw new java.io.IOException((yyline+1) + ":" + (yycolumn+1) + ": lexical error <" + yytext() + "> is a raw null character in a string.");
            }
          case 96: break;
          case 22: 
            { String err = yytext(); err = err.replace("\r", ""); err = err.replace("\n", ""); yybegin(YYINITIAL); throw new java.io.IOException((yyline+1) + ":" + (yycolumn+1) + ": lexical error <" + err + "> is not valid VSOP syntax.");
            }
          case 97: break;
          case 23: 
            { yybegin(YYINITIAL); throw new java.io.IOException((rbegin+1) + ":" + (cbegin+1) + ": lexical error <0x" + yytext() + "> is not a valid non-decimal number notation.");
            }
          case 98: break;
          case 24: 
            { yybegin(YYINITIAL); throw new java.io.IOException((rbegin+1) + ":" + (cbegin+1) + ": lexical error <0b" + yytext() + "> is not a valid non-decimal number notation.");
            }
          case 99: break;
          case 25: 
            { yypushback(1); yybegin(STRING); throw new java.io.IOException((yyline+1) + ":" + (yycolumn-1) + ": lexical error <\\x" + yytext() + "> is not a valid ASCII byte description.");
            }
          case 100: break;
          case 26: 
            { 
            }
          case 101: break;
          case 27: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { return symbol(SymbolValue.TYPE_IDENTIFIER, yytext());
            }
          case 102: break;
          case 28: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { return symbol(SymbolValue.OBJECT_IDENTIFIER, yytext());
            }
          case 103: break;
          case 29: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { return symbol(SymbolValue.INTEGER_LITERAL, Integer.parseInt(yytext()));
            }
          case 104: break;
          case 30: 
            { cbegin = yycolumn; rbegin = yyline; yybegin(BIN);
            }
          case 105: break;
          case 31: 
            { cbegin = yycolumn; rbegin = yyline; yybegin(HEX);
            }
          case 106: break;
          case 32: 
            { ccomment.push(yycolumn); rcomment.push(yyline); nesting++; yybegin(COMMENT);
            }
          case 107: break;
          case 33: 
            { return symbol(SymbolValue.ASSIGN);
            }
          case 108: break;
          case 34: 
            { return symbol(SymbolValue.LOWER_EQUAL);
            }
          case 109: break;
          case 35: 
            { String err = yytext(); err = err.replace("\r", ""); err = err.replace("\n", ""); throw new java.io.IOException((yyline+1) + ":" + (yycolumn+1+yytext().trim().length()) + ": lexical error <" + err + "> is not a well-escaped possibly multi-line string.");
            }
          case 110: break;
          case 36: 
            { throw new java.io.IOException((yyline+1) + ":" + (yycolumn+1) + ": lexical error <" + yytext() + "> is not a valid espace character in a string.");
            }
          case 111: break;
          case 37: 
            { /* ignore still in string multi-line */
            }
          case 112: break;
          case 38: 
            { string.append("\\x0a");
            }
          case 113: break;
          case 39: 
            { string.append("\\x08");
            }
          case 114: break;
          case 40: 
            { yybegin(BYTESTRING); string.append("\\x");
            }
          case 115: break;
          case 41: 
            { string.append("\\x09");
            }
          case 116: break;
          case 42: 
            { string.append("\\x0c");
            }
          case 117: break;
          case 43: 
            { string.append("\\x0d");
            }
          case 118: break;
          case 44: 
            { string.append("\\\"");
            }
          case 119: break;
          case 45: 
            { string.append("\\\\");
            }
          case 120: break;
          case 46: 
            { ccomment.push(yycolumn); rcomment.push(yyline); nesting++;
            }
          case 121: break;
          case 47: 
            { ccomment.pop(); rcomment.pop(); nesting--; if(nesting == 0) yybegin(YYINITIAL);
            }
          case 122: break;
          case 48: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { yybegin(YYINITIAL); return symbol(SymbolValue.INTEGER_LITERAL, Integer.parseInt(yytext(), 16), rbegin, cbegin);
            }
          case 123: break;
          case 49: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { yybegin(YYINITIAL); return symbol(SymbolValue.INTEGER_LITERAL, Integer.parseInt(yytext(), 2), rbegin, cbegin);
            }
          case 124: break;
          case 50: 
            { yybegin(STRING); string.append(yytext());
            }
          case 125: break;
          case 51: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { return symbol(SymbolValue.TYPE_IDENTIFIER, yytext());
            }
          case 126: break;
          case 52: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { return symbol(SymbolValue.OBJECT_IDENTIFIER, yytext());
            }
          case 127: break;
          case 53: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { return symbol(SymbolValue.INTEGER_LITERAL, Integer.parseInt(yytext()));
            }
          case 128: break;
          case 54: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 2);
            { return symbol(SymbolValue.DO);
            }
          case 129: break;
          case 55: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 2);
            { return symbol(SymbolValue.IN);
            }
          case 130: break;
          case 56: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 2);
            { return symbol(SymbolValue.IF);
            }
          case 131: break;
          case 57: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { yybegin(YYINITIAL); return symbol(SymbolValue.INTEGER_LITERAL, Integer.parseInt(yytext(), 16), rbegin, cbegin);
            }
          case 132: break;
          case 58: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { yybegin(YYINITIAL); return symbol(SymbolValue.INTEGER_LITERAL, Integer.parseInt(yytext(), 2), rbegin, cbegin);
            }
          case 133: break;
          case 59: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 3);
            { return symbol(SymbolValue.AND);
            }
          case 134: break;
          case 60: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 3);
            { return symbol(SymbolValue.NOT);
            }
          case 135: break;
          case 61: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 3);
            { return symbol(SymbolValue.NEW);
            }
          case 136: break;
          case 62: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 3);
            { return symbol(SymbolValue.LET);
            }
          case 137: break;
          case 63: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 4);
            { return symbol(SymbolValue.NULL);
            }
          case 138: break;
          case 64: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 4);
            { return symbol(SymbolValue.BOOL);
            }
          case 139: break;
          case 65: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 4);
            { return symbol(SymbolValue.ELSE);
            }
          case 140: break;
          case 66: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 4);
            { return symbol(SymbolValue.TRUE);
            }
          case 141: break;
          case 67: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 4);
            { return symbol(SymbolValue.THEN);
            }
          case 142: break;
          case 68: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 4);
            { return symbol(SymbolValue.UNIT);
            }
          case 143: break;
          case 69: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 5);
            { return symbol(SymbolValue.CLASS);
            }
          case 144: break;
          case 70: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 5);
            { return symbol(SymbolValue.FALSE);
            }
          case 145: break;
          case 71: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 5);
            { return symbol(SymbolValue.INT32);
            }
          case 146: break;
          case 72: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 5);
            { return symbol(SymbolValue.WHILE);
            }
          case 147: break;
          case 73: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 6);
            { return symbol(SymbolValue.STRING);
            }
          case 148: break;
          case 74: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 6);
            { return symbol(SymbolValue.ISNULL);
            }
          case 149: break;
          case 75: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 7);
            { return symbol(SymbolValue.EXTENDS);
            }
          case 150: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
